{
    "text": "Date: Tue, 24 Jun 2014 02:00:47 -0400 (EDT) ， From: cve-assign@.re.org ， To: vkaigoro@.hat.com ， Cc: cve-assign@.re.org, oss-security@.ts.openwall.com, ， 752395@.s.debian.org ， Subject: Re: CVE request: python: _json module is vulnerable to arbitrary process memory read ， -BEGIN PGP SIGNED MESSAGE- ， Hash: SHA1 ， > The bug is caused by allowing the user to supply a negative index ， > value. ， > http:/bugs.python.org/issue21529 ， > https:/bugs.debian.org/cgi-bin/bugreport.cgi?bug=752395 ， > https:/bugzilla.redhat.com/show_bug.cgi?id=1112285 ， > https:/hackerone.com/reports/12297 ， Use CVE-2014-4616. ， > https:/bugs.debian.org/cgi-bin/bugreport.cgi?bug=752395#5 ， > Package: python2.7 ， > https:/bugs.debian.org/cgi-bin/bugreport.cgi?bug=752395#19 ， > It affects Python 3.x in a similar way ， The same CVE ID applies to affected Python 2.x and 3.x versions. ， CVE assignment team, MITRE CVE Numbering Authority ， M/S M300 ， 202 Burlington Road, Bedford, MA 01730 USA ， [ PGP key available through http:/cve.mitre.org/cve/request_id.html ]"
}