{
    "text": "Date: Mon, 9 Dec 2013 18:41:26 -0500 (EST) ， From: cve-assign@.re.org ， To: ncoghlan@.hat.com ， Cc: cve-assign@.re.org, oss-security@.ts.openwall.com ， Subject: Re: CPython hash secret can be recoved remotely ， -BEGIN PGP SIGNED MESSAGE- ， Hash: SHA1 ， > This is a followup to CVE-2012-1150 (hash table collision CPU usage DOS ， > in CPython) ， > http:/bugs.python.org/issue14621 points out that the hash secret in ， > CPython can be recovered remotely, so while the original fix addressed ， > the \"blind DOS\" problem (of being able to DOS any Python based service ， > with a single prepared payload), it didn't completely eliminate the ， > potential for remote DOS attacks based on hash collisions. ， > (http:/bugs.python.org/issue14621#msg173455 has the details) ， > Python 3.4+ will use SipHash by default ， > (http:/www.python.org/dev/peps/pep-0456), which should resolve the ， > vulnerability completely. ， Use CVE-2013-7040. ， CVE assignment team, MITRE CVE Numbering Authority ， M/S M300 ， 202 Burlington Road, Bedford, MA 01730 USA ， [ PGP key available through http:/cve.mitre.org/cve/request_id.html ]"
}