{
    "text": "Subject : Re : CVE Request : Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler ， aligned_end is not updated ， -BEGIN PGP SIGNED MESSAGE- ， Hash : SHA1 ， On 04/25/2012 12 : 35 AM , Kurt Seifried wrote :  ， > Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler ， > aligned_end is not updated ， > does not appear to affect Python 2.x ， > memory leak/crashes/etc. ， > http : /bugs.python.org/issue14579 ， > Author : Serhiy Storchaka ( storchaka ) > In the utf-16 decoder after calling ， > unicode_decode_call_errorhandler aligned_end is not updated. This ， > may potentially cause data leaks , memory damage , and crash. The bug ， > introduced by implementation of the issue # 4868. In a similar ， > situation in the utf-8 decoder aligned_end is updated. ， > More discussion and links to the patches/etc. in the bug. ， Please use CVE-2012-2135 for this issue. ， Kurt Seifried Red Hat Security Response Team ( SRT )  ， PGP : 0x5E267993 A90B F995 7350 148F 66BF 7554 160D 4553 5E26 7993",
    "time": "Wed, 25 Apr 2012 00:37:53 -0600"
}